runtime: python39  # The runtime environment for your app

service: default


handlers:
  - url: /favicon\.png
    static_files: favicon.png
    upload: favicon\.png

  - url: /src/images
    static_dir: src/images

  - url: /src/scripts
    static_dir: src/scripts

  - url: /src/styles
    static_dir: src/styles

  - url: /
    static_files: index.html
    upload: index.html

  - url: /(.*)
    static_files: \1
    upload: .*

